### PR TITLE
Allow url to be sent through with a structured event

### PR DESCRIPTION
**Pull request by miike**
Allows page url to be sent through with structured events.

Not sure if this is the sort of interface we want (or if we want to extend this out in a similar manner to self-describing events as well)?

Thoughts @paulboocock ?

### CODE REVIEW

**Comment by paulboocock** [comment]
The issue I see here is what's going to have next. What if we want another value to the populated, the method signature just grows and grows. It also makes this inconsistent with the rest of the track methods.

I think it might be worth introducing a `page` object, like the `subject` object. This can then be injected into each track method and populate the "page" related atomic events properties. We could adopt this same concept across all of the server side trackers then. I think this idea, as it effectively makes the "page" data feel like a context, which in many ways it should be ;-) 

If you're comfortable taking a stab at the change I've suggest above, then by all means please update this PR. If not, then we'll try to find the time for it but likely in Q3 though.

**Comment by alexanderdean** [comment]
> I think this idea, as it effectively makes the "page" data feel like a context, which in many ways it should be ;-)

I think this would be nice. It would be good to design this so that it can feed into the atomic.events refactor going forwards

**Comment by miike** [comment]
So subject as it's own class object? I'm not sure if my Ruby is good enough to refactor that but I can have a go.

**Comment by paulboocock** [comment]
Yeah, Subject is currently it's own object (See subject.rb). This is currently used by being passed into the tracker constructor. 
I'm proposing making a `page.rb` that is very similar to Subject but contains things like `page_url`, `page_title` and `referrer` and other page information I'm probably forgetting right now, which can then optionally be passed into track functions as an optional final parameter.

I think as far as this PR goes, that would be fine.

Ideally, I'd like this data to be passed as a Context but we're not quite there yet to make this an easy change. Although we could perhaps built that functionality out on top of this change to keep the API clean before this release is published.
We'd want to turn the new `page.rb` into a SelfDescribingJson that, for now, we parse out of the Contexts and add to the canonical event model but later can be altered to populate as an entity just like other contexts.
Whilst this is a little out of scope of this issue specifically, it's good to have this discussion as this design will likely inform other trackers too.

**Comment by miike** [comment]
If we wanted to turn `page.rb` into a SelfDescribingJson we'd set this up as a new schema right, or should we repurpose `web_page_1`?

**Comment by paulboocock** [comment]
It'd be a new schema. For now, if this new schema existed, I'd rip out the values from the context in the tracker and populate the canonical fields but this way, it better prepares us for the future that Alex's mentions where we have refactored atomic events. Hopefully that makes sense.

**Comment by miike** [comment]
What about something like this as an intermediate solution?

```
unless context.nil?
        l = context.map {|c| c.to_json}
        page = l.find{ |c| c[:schema] == "iglu:com.snowplowanalytics.snowplow/page/jsonschema/1-0-0"}
        unless page.nil?
          page_url = r[:data]['page_url']
          pb.add('url', page_url)
        end

        pb.add_json(build_context(context), @config['encode_base64'], 'cx', 'co')
end
```

This would allow the interface to the track method to remain fundamentally the same (for the moment) and would then allow users to send through a `page` context for each method which would then get unpacked into the tracker protocol.

**Comment by miike** [comment]
@paulboocock Do you have some thoughts on the approach above?

**Comment by paulboocock** [comment]
Sorry for the delay here @miike 

The example you gave was exactly what I was trying to describe. However, I think I've sat on this a little as now that I've seen it, I'm not sure how much I like it! 🤦 

It muddles the idea of custom contexts with what we would otherwise think of "standard" atomic contexts. I think the Page context will also be an out of the box schema we would support. I also wouldn't rea;;y want to accept this with a fake schema uri, and we haven't made the decision on what to call any new schemas yet.

I think the best idea here is to introduce the `page` object, much like `subject`, that can optionally be passed into any `track` method to add the page attributes. I'm ok with it chaning the interface of the track methods, we'll likely clean these up with v1.0.0 anyway. I believe what are currently "atomic fields" will become "first party schemas" in the trackers in the future. 

Moving to this new `page` object, gives us flexibility to move it to a schema based "common" object whenever we refactor atomic events - in fact it gives us the best flexibility as we'll be able to have a toggle for populating old atomic fields or new schema fields when we get to that after the atomic events refactor.

**Comment by mscwilson** [comment]
Hello everyone. After discussion with @paulboocock, I have implemented the new Page object, which can be attached to all event types. An event Subject can now be attached as well (previously there was only the tracker's Subject).

I created a new PR #139 for this as I'd refactored a lot, so I didn't use any of your code I'm afraid @miike! Therefore I'm closing this PR.

**Comment by miike** [comment]
>so I didn't use any of your code I'm afraid @miike!

No hard feelings - that is definitely for the best. Thanks so much for getting this added in @mscwilson !

**Pull request closed without merging**
