### PR TITLE
Add tstamp to track_page_view contract

### PR DESCRIPTION
**Pull request by angelcarballo**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by angelcarballo** [comment]
Done!

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much.

**Comment by ninjabear** [comment]
Thanks @angelcarballo! This has been cherry-picked into our 0.6.0 branch which will be released soon.

**Pull request closed without merging**
